### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by mb3152** [jeffalstott/richclub#1]
Assuming X is a weighted/undirected graph, should:

RC(preserve_strength(X), scores=X.degree()).phis()

generate the same phis every time? It is for me, which seems weird. It also seems to be giving the same phis as: 

RC(X, scores=X.degree()).phis()

Also, should the normalization be done based on the total mean (i.e., the single value representing the mean of all phis), or the mean of each rank across a number of trails? In the later case, the example should be:

random = np.mean([RC(preserve_strength(X),scores=X.degree).phis() for i in range(3000)],axis=0)

Thanks

**Comment by mb3152** [comment]
I am looking at this dataset:

https://sites.google.com/site/bctnet/Home/functions/macaque71.mat?attredirects=0

**Comment by jeffalstott** [comment]
1. I'm very surprised anyone is looking at this code, let alone trying to use it!
2. preserve_strength(X) ought to return a randomized version of X, and so should be different every time. The first thing to check would be that preserve_strength(X) != X. One edge case would be if X is fully connected. Is it? If so, then I think there's nothing to permute, and  preserve_strength(X) == X. Let me know if that's the case and I can explain.

"Also, should the normalization be done based on the total mean (i.e., the single value representing the mean of all phis), or the mean of each rank across a number of trails? In the later case, the example should be:

random = np.mean([RC(preserve_strength(X),scores=X.degree).phis() for i in range(3000)],axis=0)"
You're right! I always start my code with 'from pylab import *' so I forget about non-numpy means!

**Comment by mb3152** [comment]
Well, it's a very nice codebase, and I use iGraph for all my graph theory stuff, so it works out well! 

It looks like in preserve_strength(X), the edge weights are changing, but none of the edges are actually changing. 

x = np.array(preserve_strength(graph).get_adjacency(attribute='weight').data)==np.array(graph.get_adjacency(attribute='weight').data)
len(x[x==False])
3486

x = np.array(preserve_strength(graph).get_adjacency().data)==np.array(graph.get_adjacency().data)
len(x[x==False])
0.0

Is that what you meant to do?

**Comment by jeffalstott** [comment]
By default randomize_topology=False. If you want to change the edges as well, then set randomize_topology=True when calling preserve_strength.

Is the degree sequence unique? That is, every node's degree is unique? That would be another situation in which there are no degrees of freedom on which to permute strength.

**Comment by mb3152** [comment]
Ah, the degree sequence is unique, and I get how it works now. Does randomize_topology keep the same degree of each node, but change the edges? That seems like a nice random control.

**Comment by jeffalstott** [comment]
"Does randomize_topology keep the same degree of each node, but change the
edges?"

Yes.

"That seems like a nice random control."
I recommend reading our paper on the subject, where we drill down into what
exactly is the "right" control to be using. It requires very clear and
deliberate thinking about what *exactly *one is trying to say.

**Comment by mb3152** [comment]
Yes, Figure 2 is quite nice. Thanks for the help!

**Comment by mb3152** [comment]
Sorry, one more check: the order of the returned array of phis is in ascending order of the rank, right? So the lowest degree threshold rank phi is the first entry [0], and highest rank phi is last in the array [-1]? That's what your code looks like and my results look like, but I just wanted to make sure.

**Comment by jeffalstott** [comment]
It should be!
